version: "3.8"

services:
  cache:
    container_name: seating_redis
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  api:
    container_name: seating-backend
    build:
      context: ./
      target: production
    image: keshavmakkad10/seating-backend
    depends_on:
      - cache
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      # DB_HOST: db
      # DB_PORT: 5432
      # DB_USER: postgres
      # DB_PASSWORD: postgres
      # DB_NAME: postgres
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    links:
      - cache
    volumes:
      - ./:/src

volumes:
  cache:
    driver: local